/*
 * This source file was generated by the Gradle 'init' task
 */
package co.edu.unal.bog_2016699_2026_1.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
