/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":algorithm"))
}

application {
    // Define the main class for the application.
    mainClass = "co.edu.unal.bog2016699s2026m1.app.App"
}
