/*
 * This source file was generated by the Gradle 'init' task
 */
package co.edu.unal.bog2016699s2026m1.algorithm;

import co.edu.unal.bog2016699s2026h1.structures.LinkedList;

class JoinUtils {
	public static String join(LinkedList source) {
		StringBuilder result = new StringBuilder();
		for (int i = 0; i < source.size(); ++i) {
			if (result.length() > 0) {
				result.append(" ");
			}
			result.append(source.get(i));
		}

		return result.toString();
	}
}
