/*
 * This source file was generated by the Gradle 'init' task
 */
package co.edu.unal.bog2016699s2026m1.algorithm;

import co.edu.unal.bog2016699s2026h1.structures.LinkedList;

public class StringUtils {
	public static String join(LinkedList source) {
		return JoinUtils.join(source);
	}

	public static LinkedList split(String source) {
		return SplitUtils.split(source);
	}
}
