/*
 * This source file was generated by the Gradle 'init' task
 */
package co.edu.unal.bog2016699s2026m1.app;

import static co.edu.unal.bog2016699s2026m1.algorithm.StringUtils.join;
import static co.edu.unal.bog2016699s2026m1.algorithm.StringUtils.split;
import static co.edu.unal.bog2016699s2026m1.app.MessageUtils.getMessage;

import co.edu.unal.bog2016699s2026h1.structures.LinkedList;

public class App {
	public static void main(String[] args) {
		LinkedList tokens;
		tokens = split(getMessage());
		String result = join(tokens);
		System.out.println(result.toUpperCase());
	}
}
