/*
 * This source file was generated by the Gradle 'init' task
 */
package co.edu.unal.bog2016699s2026m1.app;

class MessageUtils {
	public static String getMessage() {
		return "Hello      World!";
	}
}
